export const trendingProducts: IProducts[] = [
  {
    id: 1,
    img: "/product-5-600x600.jpg",
    cat: "GoPro",
    title: "Sonos Beam Gen 2 Soundbar",
    price: 930.0,
    reviews: 8,
    type: "sale",
    badge: "sale",
    sale: 44,
  },
  {
    id: 2,
    img: "/product-19-600x600.jpg",
    cat: "Global Office",
    title: "Bose Smart Soundbar 900",
    price: 689.0,
    reviews: 9,
    type: "featured",
    badge: "hot",
  },
  {
    id: 3,
    img: "/product-17-600x600.jpg",
    cat: "Young Shop",
    title: "JBL Bar 9.1 Soundbar with Dolby Atmos",
    price: 1464.0,
    reviews: 10,
    type: "trending",
    badge: "sale",
    sale: 44,
  },
  {
    id: 4,
    img: "/product-7-600x600.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 294.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
];

export const dealOfTheDay: IProducts[] = [
  {
    id: 1,
    img: "/product-3-600x600.jpg",
    cat: "GoPro",
    title: "Sonos Beam Gen 2 Soundbar",
    price: 930.0,
    reviews: 8,
    type: "sale",
    badge: "sale",
    sale: 44,
  },
  {
    id: 2,
    img: "/product-20-150x150.jpg",
    cat: "Global Office",
    title: "Bose Smart Soundbar 900",
    price: 689.0,
    reviews: 9,
    type: "featured",
    badge: "hot",
  },
  {
    id: 3,
    img: "/product-17-600x600.jpg",
    cat: "Young Shop",
    title: "JBL Bar 9.1 Soundbar with Dolby Atmos",
    price: 1464.0,
    reviews: 10,
    type: "trending",
    badge: "sale",
    sale: 44,
  },
  {
    id: 4,
    img: "/product-7-600x600.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 294.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
];

export const categories: ICategories[] = [
  {
    img: "/1.png",
    title: "Headphones",
    count: "5 products",
    link: "category/headphones",
  },
  {
    img: "/2.png",
    title: "With Bluetooth",
    count: "7 products",
    link: "category/bluetooth",
  },
  {
    img: "/3.png",
    title: "Mobile Phone",
    count: "5 products",
    link: "category/mobile",
  },
  {
    img: "/4.png",
    title: "CPU Heat Pipes",
    count: "7 products",
    link: "category/cpu",
  },
  {
    img: "/5.png",
    title: "Smart Watch",
    count: "6 products",
    link: "category/smart-watch",
  },
];

export const bluetooth: IProducts[] = [
  {
    id: 1,
    img: "/product-5-600x600.jpg",
    cat: "GoPro",
    title: "Sonos Beam Gen 2 Soundbar",
    price: 930.0,
    reviews: 8,
    type: "sale",
    badge: "sale",
    sale: 44,
  },
  {
    id: 2,
    img: "/product-19-600x600.jpg",
    cat: "Global Office",
    title: "Bose Smart Soundbar 900",
    price: 689.0,
    reviews: 9,
    type: "featured",
    badge: "hot",
  },
  {
    id: 3,
    img: "/product-17-600x600.jpg",
    cat: "Young Shop",
    title: "JBL Bar 9.1 Soundbar with Dolby Atmos",
    price: 1464.0,
    reviews: 10,
    type: "trending",
    badge: "sale",
    sale: 44,
  },
  {
    id: 4,
    img: "/product-7-600x600.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 294.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
];

export const cpu: IProducts[] = [
  {
    id: 1,
    img: "/product-5-600x600.jpg",
    cat: "GoPro",
    title: "Sonos Beam Gen 2 Soundbar",
    price: 930.0,
    reviews: 8,
    type: "sale",
    badge: "sale",
    sale: 44,
  },
  {
    id: 2,
    img: "/product-19-600x600.jpg",
    cat: "Global Office",
    title: "Bose Smart Soundbar 900",
    price: 689.0,
    reviews: 9,
    type: "featured",
    badge: "hot",
  },
  {
    id: 3,
    img: "/product-17-600x600.jpg",
    cat: "Young Shop",
    title: "JBL Bar 9.1 Soundbar with Dolby Atmos",
    price: 1464.0,
    reviews: 10,
    type: "trending",
    badge: "sale",
    sale: 44,
  },
  {
    id: 4,
    img: "/product-7-600x600.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 294.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
  {
    id: 5,
    img: "/product-20-150x150.jpg",
    cat: "Global Office",
    title: "Bose Smart Soundbar 900",
    price: 689.0,
    reviews: 9,
    type: "featured",
    badge: "hot",
  },
];
