export const trendingProducts: IProducts[] = [
  {
    id: 1,
    img: "/product-5-600x600.jpg",
    cat: "GoPro",
    title: "Sonos Beam Gen 2 Soundbar",
    price: 930.0,
    reviews: 8,
    type: "sale",
    badge: "sale",
    sale: 44,
  },
  {
    id: 2,
    img: "/product-19-600x600.jpg",
    cat: "Global Office",
    title: "Bose Smart Soundbar 900",
    price: 689.0,
    reviews: 9,
    type: "featured",
    badge: "hot",
  },
  {
    id: 3,
    img: "/product-17-600x600.jpg",
    cat: "Young Shop",
    title: "JBL Bar 9.1 Soundbar with Dolby Atmos",
    price: 1464.0,
    reviews: 10,
    type: "trending",
    badge: "sale",
    sale: 44,
  },
  {
    id: 4,
    img: "/product-7-600x600.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 294.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
];

export const dealOfTheDay: IProducts[] = [
  {
    id: 1,
    img: "/product-3-600x600.jpg",
    cat: "GoPro",
    title: "Sonos Beam Gen 2 Soundbar",
    price: 930.0,
    reviews: 8,
    type: "sale",
    badge: "sale",
    sale: 44,
  },
  {
    id: 2,
    img: "/product-20-150x150.jpg",
    cat: "Global Office",
    title: "Bose Smart Soundbar 900",
    price: 689.0,
    reviews: 9,
    type: "featured",
    badge: "hot",
  },
  {
    id: 3,
    img: "/product-17-600x600.jpg",
    cat: "Young Shop",
    title: "JBL Bar 9.1 Soundbar with Dolby Atmos",
    price: 1464.0,
    reviews: 10,
    type: "trending",
    badge: "sale",
    sale: 44,
  },
  {
    id: 4,
    img: "/product-7-600x600.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 294.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
  {
    id: 5,
    img: "/product-7-600x600.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 294.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
];

export const categories: ICategories[] = [
  {
    img: "/1.png",
    title: "Headphones",
    count: "5 products",
    link: "category/headphones",
  },
  {
    img: "/2.png",
    title: "With Bluetooth",
    count: "7 products",
    link: "category/bluetooth",
  },
  {
    img: "/3.png",
    title: "Mobile Phone",
    count: "5 products",
    link: "category/mobile",
  },
  {
    img: "/4.png",
    title: "CPU Heat Pipes",
    count: "7 products",
    link: "category/cpu",
  },
  {
    img: "/5.png",
    title: "Smart Watch",
    count: "6 products",
    link: "category/smart-watch",
  },
];

export const bluetooth: IProducts[] = [
  {
    id: 1,
    img: "/product-5-600x600.jpg",
    cat: "GoPro",
    title: "Sonos Beam Gen 2 Soundbar",
    price: 930.0,
    reviews: 8,
    type: "sale",
    badge: "sale",
    sale: 44,
  },
  {
    id: 2,
    img: "/product-19-600x600.jpg",
    cat: "Global Office",
    title: "Bose Smart Soundbar 900",
    price: 689.0,
    reviews: 9,
    type: "featured",
    badge: "hot",
  },
  {
    id: 3,
    img: "/product-17-600x600.jpg",
    cat: "Young Shop",
    title: "JBL Bar 9.1 Soundbar with Dolby Atmos",
    price: 1464.0,
    reviews: 10,
    type: "trending",
    badge: "sale",
    sale: 44,
  },
  {
    id: 4,
    img: "/product-7-600x600.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 294.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
];

export const cpu: IProducts[] = [
  {
    id: 1,
    img: "/product-5-600x600.jpg",
    cat: "GoPro",
    title: "Sonos Beam Gen 2 Soundbar",
    price: 930.0,
    reviews: 8,
    type: "sale",
    badge: "sale",
    sale: 44,
  },
  {
    id: 2,
    img: "/product-19-600x600.jpg",
    cat: "Global Office",
    title: "Bose Smart Soundbar 900",
    price: 689.0,
    reviews: 9,
    type: "featured",
    badge: "hot",
  },
  {
    id: 3,
    img: "/product-17-600x600.jpg",
    cat: "Young Shop",
    title: "JBL Bar 9.1 Soundbar with Dolby Atmos",
    price: 1464.0,
    reviews: 10,
    type: "trending",
    badge: "sale",
    sale: 44,
  },
  {
    id: 4,
    img: "/product-7-600x600.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 294.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
  {
    id: 5,
    img: "/product-20-150x150.jpg",
    cat: "Global Office",
    title: "Bose Smart Soundbar 900",
    price: 689.0,
    reviews: 9,
    type: "featured",
    badge: "hot",
  },
];

export const storeData: IStore[] = [
  {
    id: 1,
    title: "Go Pro",
    reviews: 58,
    location: "48027 Roob Drives, Lake Jeremie, Ohio, BT",
    phone: "+19516391057",
    email: "mcglynn.ken@example.net",
    img: "1 (1).png",
  },
  {
    id: 2,
    title: "Global Office",
    reviews: 71,
    location: "69819 Hermann Junction, Rogahntown, Michigan, VE",
    phone: "+12569206020",
    email: "gbruen@example.org",
    img: "7.png",
  },
  {
    id: 3,
    title: "Young Shop",
    reviews: 71,
    location: "69819 Hermann Junction, Rogahntown, Michigan, VE",
    phone: "+12569206020",
    email: "gbruen@example.org",
    img: "7.png",
  },
  {
    id: 4,
    title: "Global Store",
    reviews: 71,
    location: "69819 Hermann Junction, Rogahntown, Michigan, VE",
    phone: "+12569206020",
    email: "gbruen@example.org",
    img: "7.png",
  },
  {
    id: 5,
    title: "Roberts Store",
    reviews: 60,
    location: "69819 Hermann Junction, Rogahntown, Michigan, VE",
    phone: "+12569206020",
    email: "gbruen@example.org",
    img: "7.png",
  },
  {
    id: 6,
    title: "Stouffer",
    reviews: 80,
    location: "69819 Hermann Junction, Rogahntown, Michigan, VE",
    phone: "+12569206020",
    email: "gbruen@example.org",
    img: "1 (1).png",
  },
  {
    id: 7,
    title: "StarKist",
    reviews: 80,
    location: "69819 Hermann Junction, Rogahntown, Michigan, VE",
    phone: "+12569206020",
    email: "gbruen@example.org",
    img: "1 (1).png",
  },
  {
    id: 8,
    title: "Old El Passo",
    reviews: 30,
    location: "69819 Hermann Junction, Rogahntown, Michigan, VE",
    phone: "+12569206020",
    email: "gbruen@example.org",
    img: "1 (1).png",
  },
];

export const shop: IProducts[] = [
  {
    id: 1,
    img: "/product-5-600x600.jpg",
    cat: "GoPro",
    title: "Sonos Beam Gen 2 Soundbar",
    price: 930.0,
    reviews: 8,
    type: "sale",
    badge: "sale",
    sale: 44,
  },
  {
    id: 2,
    img: "/product-19-600x600.jpg",
    cat: "Global Office",
    title: "Bose Smart Soundbar 900",
    price: 689.0,
    reviews: 9,
    type: "featured",
    badge: "hot",
  },
  {
    id: 3,
    img: "/product-17-600x600.jpg",
    cat: "Young Shop",
    title: "JBL Bar 9.1 Soundbar with Dolby Atmos",
    price: 1464.0,
    reviews: 10,
    type: "trending",
    badge: "sale",
    sale: 44,
  },
  {
    id: 4,
    img: "/product-7-600x600.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 294.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
  {
    id: 5,
    img: "/1.jpg",
    cat: "StarKist",
    title: "Oraimo FreePods Lite True Wireless Earbuds Bluetooth",
    price: 294.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
  {
    id: 6,
    img: "/2.jpg",
    cat: "StarKist",
    title: "Xiaomi Mi Power Bank 50W 20000mAh High Capacity Portable Battery",
    price: 300.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
  {
    id: 7,
    img: "/tv1.jpg",
    cat: "StarKist",
    title:
      "Samsung 55 Inch TV Crystal Processor 4K LED with Built-in Receiver ",
    price: 3000.0,
    reviews: 8,
    type: "top reated",
    sale: 44,
    badge: "sale",
  },
];

export const newArrival = [
  {
    id: 1,
    img: "/tv1.jpg",
    cat: "StarKist",
    title: "Samsung 55 Inch TV Crystal Processor 4K LED with Built-in Receiver",
    price: 3000.0,
    reviews: 8,
    type: "top reated",
    sale: 44,
    badge: "sale",
  },
  {
    id: 2,
    img: "/headp1.jpg",
    cat: "StarKist",
    title: "soundcore Anker Life P25i True Wireless Earbuds, AI-Enhanced Calls",
    price: 300.0,
    reviews: 8,
    type: "top reated",
    sale: 30,
    badge: "sale",
  },
  {
    id: 3,
    img: "/3.jpg",
    cat: "StarKist",
    title: "soundcore Anker Life P25i True Wireless Earbuds, AI-Enhanced Calls",
    price: 410.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
  {
    id: 4,
    img: "/4.jpg",
    cat: "StarKist",
    title: "Xiaomi Mi Box S (2nd Gen) with 4K Ultra HD Streaming",
    price: 20.0,
    reviews: 8,
    type: "top reated",
    sale: 15,
    badge: "sale",
  },
  {
    id: 5,
    img: "/5.jpg",
    cat: "StarKist",
    title: "S-H151 Type-C Male to USB Female Adapter-Maize",
    price: 30.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
];

export const sale: ITopRated[] = [
  {
    img: "/product-5-600x600.jpg",
    cat: "GoPro",
    title: "Sonos Beam Gen 2 Soundbar",
    price: 930.0,
    reviews: 8,
  },
  {
    img: "/product-details-desc-2-150x150.jpg",
    cat: "Global Office",
    title: "Sennheiser Ambeo Soundbar (Digital)",
    price: 689.0,
    reviews: 9,
  },
  {
    img: "/product-7-150x150.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 1464.0,
    reviews: 10,
  },
];
export const trending: ITopRated[] = [
  {
    img: "/product-11-150x150.jpg",
    cat: "Stouffer",
    title: "Elgato Stream Deck XL",
    price: 930.0,
    reviews: 8,
  },
  {
    img: "/product-20-150x150.jpg",
    cat: "GoPro",
    title: "ASUS ROG Swift PG279QM 27-Inch Gaming Monitor",
    price: 93.0,
    reviews: 9,
  },
  {
    img: "/product-2-150x150.jpg",
    cat: "StarKist",
    title: "Hisense U8G Quantum Series 4K ULED Android TV (Digital)",
    price: 762.72,
    reviews: 10,
  },
];
export const topRated: ITopRated[] = [
  {
    img: "/product-11-150x150.jpg",
    cat: "Stouffer",
    title: "Elgato Stream Deck XL",
    price: 930.0,
    reviews: 8,
  },
  {
    img: "/product-7-150x150.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 1464.0,
    reviews: 10,
  },
  {
    img: "/product-18-150x150.jpg",
    cat: "StarKist",
    title: "Nintendo Switch OLED Model",
    price: 762.72,
    reviews: 10,
  },
];

export const computerSection: IProducts[] = [
  {
    id: 1,
    img: "/product-5-600x600.jpg",
    cat: "GoPro",
    title: "Sonos Beam Gen 2 Soundbar",
    price: 930.0,
    reviews: 8,
    type: "sale",
    badge: "sale",
    sale: 44,
  },
  {
    id: 2,
    img: "/product-19-600x600.jpg",
    cat: "Global Office",
    title: "Bose Smart Soundbar 900",
    price: 689.0,
    reviews: 9,
    type: "featured",
    badge: "hot",
  },
  {
    id: 3,
    img: "/product-17-600x600.jpg",
    cat: "Young Shop",
    title: "JBL Bar 9.1 Soundbar with Dolby Atmos",
    price: 1464.0,
    reviews: 10,
    type: "trending",
    badge: "sale",
    sale: 44,
  },
  {
    id: 4,
    img: "/product-7-600x600.jpg",
    cat: "StarKist",
    title: "Sony HT-A9 Home Theater System",
    price: 294.0,
    reviews: 8,
    type: "top reated",
    badge: "hot",
  },
];
